In [1]:
print("hello")

hello


# Import Library: Numpy

In [4]:
import numpy as np
#check version 
print(np.__version__)

2.5.3


# Datatypes of Numpy 

ndarray

In [11]:
#1- dimentional array as a vector
a1 = np.array([1,2,3])
a1.shape, a1.dtype, a1.ndim, type(a1)

((3,), dtype('int64'), 1, numpy.ndarray)

In [18]:
# 2 - dimentional array, referred as matrix
a2 = np.array([
    [1,2,3.7],
    [4,5,6],
])
a2.shape, a2.dtype, a2.ndim, type(a2)

((2, 3), dtype('float64'), 2, numpy.ndarray)

In [25]:
# 3 -dimentional array , aslo referred as matrix
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18],
        
    ]
])
a3.shape, a3.dtype, a3.ndim, type(a3)

((2, 3, 3), dtype('int64'), 3, numpy.ndarray)

In [26]:
a1

array([1, 2, 3])

In [27]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Anatomy of an array 

key terms:
- array: a list of numbers, can be multi dimentional
- scalar: a single number 
- vector: list of numbers with one dimention
- metrix: multi dimentional array


# Creation of Arrays with numpy

In [32]:
simple_array = np.array([1,2,3])
simple_array,     simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

- create only ones numbers in the array

In [34]:
# Create only ones array (the default type is float)
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
#we write astype to change the array's type to the type that we want
ones.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- create only zeroes numbers in the array

In [ ]:
zeros = np.zeros((3,3,6))
zeros 

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

- Create an array whithin a range 

In [47]:
#Create an array whithin a range of value 
range_array = np.arange(0,10)
range_array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Create random array

In [ ]:
#Random with specfic datatype
random_array= np.random.randint(10, size=(5,3))
random_array

array([[8, 4, 9],
       [6, 4, 9],
       [5, 5, 3],
       [7, 5, 9],
       [6, 5, 3]], dtype=int32)

In [ ]:
#Random with flaot 
np.random.random((5,3)) # random float number between 0 and 1

array([[0.04902725, 0.11675319, 0.07570763],
       [0.92325191, 0.9090915 , 0.20397339],
       [0.05293406, 0.92759486, 0.61420587],
       [0.54034316, 0.28602309, 0.37765943],
       [0.57896826, 0.64747427, 0.30532997]])

# Indexing Arrays and Matrices


In [59]:
a1

array([1, 2, 3])

In [61]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Array shapes are in format: (row, column, n, n,...) where i = n is opetional extra dimention

In [65]:
a1[0]

np.int64(1)

In [66]:
a2[0]

array([1. , 2. , 3.7])

In [67]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#get the second row (index 1) in a2
a2[1]

array([4., 5., 6.])

In [72]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 2, 9, 7, 7],
         [1, 1, 4, 0, 2],
         [5, 1, 5, 6, 4],
         [4, 3, 3, 0, 1]],

        [[0, 6, 1, 0, 1],
         [5, 2, 3, 6, 9],
         [6, 2, 0, 1, 7],
         [0, 2, 1, 2, 0]],

        [[1, 6, 0, 1, 9],
         [1, 8, 8, 1, 1],
         [7, 8, 9, 3, 4],
         [2, 7, 5, 1, 5]]],


       [[[9, 7, 1, 7, 9],
         [2, 3, 7, 7, 9],
         [5, 4, 5, 0, 7],
         [2, 1, 6, 1, 2]],

        [[4, 3, 5, 6, 6],
         [4, 5, 1, 4, 3],
         [3, 6, 3, 5, 7],
         [1, 6, 3, 4, 8]],

        [[2, 6, 6, 5, 5],
         [4, 4, 5, 5, 8],
         [8, 9, 1, 5, 9],
         [6, 3, 4, 2, 5]]]], dtype=int32)

In [73]:
a4.shape

(2, 3, 4, 5)

In [74]:
#get only first 4 numbers of each single vector
a4[:,:,:,4]

array([[[7, 2, 4, 1],
        [1, 9, 7, 0],
        [9, 1, 4, 5]],

       [[9, 9, 7, 2],
        [6, 3, 7, 8],
        [5, 8, 9, 5]]], dtype=int32)