In [11]:
print("hello")

hello


# Import Library: Numpy

In [33]:
import numpy as np
#check version 
print(np.__version__)

2.5.3


# Datatypes of Numpy 

ndarray

In [21]:
#1- dimentional array as a vector
a1 = np.array([1,2,3])
a1.shape, a1.dtype, a1.ndim, type(a1)

((3,), dtype('int64'), 1, numpy.ndarray)

In [22]:
# 2 - dimentional array, referred as matrix
a2 = np.array([
    [1,2,3.7],
    [4,5,6],
])
a2.shape, a2.dtype, a2.ndim, type(a2)

((2, 3), dtype('float64'), 2, numpy.ndarray)

In [34]:
# 3 -dimentional array , aslo referred as matrix
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18],
        
    ]
])
a3.shape, a3.dtype, a3.ndim, type(a3)

((2, 3, 3), dtype('int64'), 3, numpy.ndarray)

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Anatomy of an array 

key terms:
- array: a list of numbers, can be multi dimentional
- scalar: a single number 
- vector: list of numbers with one dimention
- metrix: multi dimentional array


# Creation of Arrays with numpy

In [ ]:
simple_array = np.array([1,2,3])
simple_array,     simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

- create only ones numbers in the array

In [ ]:
# Create only ones array (the default type is float)
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#we write astype to change the array's type to the type that we want
ones.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- create only zeroes numbers in the array

In [ ]:
zeros = np.zeros((3,3,6))
zeros 

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

- Create an array whithin a range 

In [ ]:
#Create an array whithin a range of value 
range_array = np.arange(0,10)
range_array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Create random array

In [94]:
#Random with specfic datatype
random_array= np.random.randint(10, size=(5,3))
random_array

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [ ]:
#Random with flaot 
np.random.random((5,3)) # random float number between 0 and 1

array([[0.04902725, 0.11675319, 0.07570763],
       [0.92325191, 0.9090915 , 0.20397339],
       [0.05293406, 0.92759486, 0.61420587],
       [0.54034316, 0.28602309, 0.37765943],
       [0.57896826, 0.64747427, 0.30532997]])

# Indexing Arrays and Matrices


In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Array shapes are in format: (row, column, n, n,...) where i = n is opetional extra dimention

In [ ]:
a1[0]

np.int64(1)

In [ ]:
a2[0]

array([1. , 2. , 3.7])

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#get the second row (index 1) in a2
a2[1]

array([4., 5., 6.])

In [112]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 3, 6, 9, 8],
         [0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6]],

        [[5, 7, 8, 8, 9],
         [2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6]],

        [[5, 7, 0, 8, 4],
         [6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9]]],


       [[[9, 9, 7, 3, 2],
         [3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2]],

        [[5, 5, 0, 8, 1],
         [1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1]],

        [[2, 1, 4, 2, 5],
         [5, 5, 2, 5, 7],
         [7, 6, 1, 6, 7],
         [2, 3, 1, 9, 5]]]], dtype=int32)

In [ ]:
a4.shape

(2, 3, 4, 5)

In [114]:
#get only first 4 numbers of each single vector
a4[:,:,:,4]

array([[[8, 0, 1, 6],
        [9, 9, 3, 6],
        [4, 3, 4, 9]],

       [[2, 5, 1, 2],
        [1, 8, 3, 1],
        [5, 7, 7, 5]]], dtype=int32)

# Manipulating and Comparing arrays
 

- Arithmetic:
    - +,-,/, // , == , %
   - np.exp()
   - np.log()
   - Dot product - np.dot()
   - Broadcasting (make operations on mulidimentional arrays - they have to be same size)

- Aggregation
  - np.sum() 
   - faster than Python's sum() for NumPy arrays
   - np.mean()
   - np.std()
   -np.var()
   - np.min()
   - np.max()
   -np.argmin() - find index of minimum value
   - np.argmax() - find index of maximum value
   - These work on all ndarray's:
      * a4.min(axis=0)-- yoe can use axis as well

* Reshaping
    * np.reshaping()
 * Transposing
    * a3.T
* Comparison Operators
    * <,>, <=, >= , != , ==, np.sum(x>3)
    




# Arithmetic

In [ ]:
a1

array([1, 2, 3])

In [ ]:
b1 = np.array([3,2,1])
b1

array([3, 2, 1])

In [ ]:
#add 2 arrays
a1 + b1

array([4, 4, 4])

In [ ]:
# subtract 2 arrays
a1 - b1

array([-2,  0,  2])

In [ ]:
#multiply 2 arrays
a1 * b1

NameError: name 'a1' is not defined

In [ ]:
a2 + 2

array([[3. , 4. , 5.7],
       [6. , 7. , 8. ]])

In [ ]:
#take an array to the power
a2 **2

array([[ 1.  ,  4.  , 13.69],
       [16.  , 25.  , 36.  ]])

In [ ]:
#take an array to the power
np.square(a2)

array([[ 1.  ,  4.  , 13.69],
       [16.  , 25.  , 36.  ]])

In [ ]:
a1% 2

array([1, 0, 1])

In [ ]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Aggregation

In [5]:
a1

array([1, 2, 3])

In [7]:
sum(a1)

np.int64(6)

In [9]:
np.sum(a1)

np.int64(6)

In [11]:
massive_array = np.random.random(100000)
massive_array.size, type(massive_array )

(100000, numpy.ndarray)

In [13]:
#find the mean 
np.mean(a1)

np.float64(2.0)

In [16]:
#st (standard divaition) - or var*2
np.std(a1)

np.float64(0.816496580927726)

In [19]:
np.sqrt(np.var(a1))

np.float64(0.816496580927726)

In [17]:
# varaince - is the average*2 - mean 
np.var(a1)


np.float64(0.6666666666666666)

# Reshaping 
we use it in images (it's array of numbers) we need to reshape the image to make it readable for the model

In [25]:
a2


array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [27]:
a2.shape

(2, 3)

In [93]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [38]:
a2.reshape(2,3,1) + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.7, 11.7, 12.7]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22. , 23. , 24. ]]])

# Transpose (reverse)

In [52]:
a2.T 

array([[1. , 4. ],
       [2. , 5. ],
       [3.7, 6. ]])

In [54]:
a2.transpose()

array([[1. , 4. ],
       [2. , 5. ],
       [3.7, 6. ]])

In [56]:
a2.T.shape

(3, 2)

In [62]:
matrix = np.random.randint(10 , size=(5,4,3))
matrix

array([[[3, 2, 2],
        [7, 6, 7],
        [9, 2, 4],
        [2, 2, 6]],

       [[3, 7, 3],
        [7, 0, 2],
        [3, 5, 1],
        [6, 7, 7]],

       [[0, 7, 4],
        [0, 4, 2],
        [6, 7, 3],
        [4, 9, 4]],

       [[7, 4, 8],
        [6, 0, 3],
        [4, 5, 6],
        [9, 9, 0]],

       [[4, 5, 3],
        [8, 3, 1],
        [7, 6, 6],
        [7, 6, 4]]], dtype=int32)

In [64]:
matrix.T

array([[[3, 3, 0, 7, 4],
        [7, 7, 0, 6, 8],
        [9, 3, 6, 4, 7],
        [2, 6, 4, 9, 7]],

       [[2, 7, 7, 4, 5],
        [6, 0, 4, 0, 3],
        [2, 5, 7, 5, 6],
        [2, 7, 9, 9, 6]],

       [[2, 3, 4, 8, 3],
        [7, 2, 2, 3, 1],
        [4, 1, 3, 6, 6],
        [6, 7, 4, 0, 4]]], dtype=int32)

In [66]:
matrix.T.shape

(3, 4, 5)

# Dot Product 
The main two rules for dot product to remember are:
1. The inner dimention must match:
* (3,2) @ (3,2) won't work
* (2,3) @ (2,3) will work 
* (3,2) @ (2,3) will work 

2.The resulting matrix has the shape of the outer dimetions:
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

NOTE: In NumPy, np.dot() and @ can be used to achive the same result for 1-2 dimention arrays. However, their behaviour begind to differ at arrays with 3 + dimenstions.

In [73]:
np.random.seed(0)   # .seed(0) t avoid changing the result 
mat1 =np.random.randint(10, size = (3,3))
mat2 =np.random.randint(10, size = (3,2))

mat1.shape , mat2.shape

((3, 3), (3, 2))

In [74]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [ ]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]], dtype=int32)

In [77]:
np.dot(mat1,mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

In [79]:
mat1 @ mat2      # same result

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

# Comparison Operators
Finding out if one matrix is larger , smaller, or equal to another.( by comparing element by element)

In [81]:
a1

array([1, 2, 3])

In [83]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [86]:
 a1 >=a2   

array([[ True,  True, False],
       [False, False, False]])

In [90]:
a1 > 5

array([False, False, False])

In [91]:
a1 == a1

array([ True,  True,  True])

# Sorting Arrays 
* np.sort() - sort values in specified dimention of an array.
* np.argsort() - return the indices to sort the array on a given axis.
* np.argmax() - return the index/indices which gives the highest value(s) along axis.
* np.argmin() - return the index/indices which gives the lowest value(s) along an axis.

In [97]:
random_array

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [99]:
np.sort(random_array)   

array([[6, 7, 7],
       [1, 5, 8],
       [8, 9, 9],
       [0, 3, 4],
       [0, 3, 5]], dtype=int32)

In [101]:
np.argsort(random_array)

array([[0, 1, 2],
       [1, 2, 0],
       [1, 0, 2],
       [2, 1, 0],
       [2, 0, 1]])

In [103]:
np.argmax(random_array)

np.int64(6)

In [105]:
a2

array([[1. , 2. , 3.7],
       [4. , 5. , 6. ]])

In [107]:
np.argmax(a2, axis = 1)

array([2, 2])

In [108]:
np.argmin(a2,axis= 1)

array([0, 0])