# NumPy Challenge Exercises 

In [15]:

import numpy as np

# Set a seed so everyone gets the same "random" numbers and answers are checkable
np.random.seed(42)
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


1. Setup & Array Attributes
Skills: np.array, .shape, .ndim, .dtype, .size

Exercise 1.1 ⭐ — Create a 1D array (vector) called temps holding these daily temperatures: 18, 21, 23, 19, 25, 22, 20. Then print its shape, number of dimensions, dtype, and size on one line.

In [10]:
temps = np.array([8, 21, 23, 19, 25, 22, 2])
temps 


array([ 8, 21, 23, 19, 25, 22,  2])

In [14]:
temps.shape,temps.ndim, temps.dtype, temps.size

((7,), 1, dtype('int64'), 7)

Exercise 1.2 ⭐ — Create a 2D array (matrix) called grid with 3 rows and 4 columns (use any numbers you like). Confirm with .shape that it really is (3, 4) and that .ndim is 2.

In [17]:
grid = np.array([
    [5,3,8,8],
    [9,0,5,3],
    [7,4,2,1],

])
grid.shape, grid.ndim

((3, 4), 2)

Exercise 1.3 ⭐⭐ — Build this 3D array by hand: a stack of 2 matrices, each 2 x 2, so the final shape is (2, 2, 2). Fill it with the numbers 1 through 8 in order. Verify .shape and .size.

In [22]:
ones_array = np.array([
    [
        [1,1],
        [1,1],
    ],
    [
        [1,1],
        [1,1],
    ]
])
ones_array 

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [26]:
ones_array.shape

(2, 2, 2)

Exercise 1.4 ⭐⭐ — Create an array from the list [1, 2, 3.5]. Before you run it, predict the dtype, then check it. Why does it come out the way it does? (Write your reasoning as a comment.)

In [28]:
arr = np.array([1,2,3.5])    # the dtype is ganne be float because 3.5 is float so ir will consider the whole array as float 

In [29]:
arr.dtype

dtype('float64')

# 2. Creating Arrays

Exercise 2.1 ⭐ — Create a 4 x 5 array of all ones, then a 2 x 3 x 3 array of all zeros.

In [33]:
ones_array = np.ones((4,5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
zeros_array= np.zeros((2,3,3))
zeros_array


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Exercise 2.2 ⭐ — Use np.arange to create an array of the even numbers from 0 to 20 inclusive (i.e. 0, 2, 4, ..., 20).

In [35]:
even_nums = np.arange(0,21,2)
even_nums

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Exercise 2.3 ⭐⭐ — Create a 4 x 4 array of random integers between 0 and 9. Then convert it to floats using .astype() and confirm the new dtype.

In [43]:
random_array = np.random.randint(10,size = (4,4))

random_array

array([[4, 0, 9, 5],
       [8, 0, 9, 2],
       [6, 3, 8, 2],
       [4, 2, 6, 4]], dtype=int32)

In [45]:
random_array.astype(float)

array([[4., 0., 9., 5.],
       [8., 0., 9., 2.],
       [6., 3., 8., 2.],
       [4., 2., 6., 4.]])

Exercise 2.4 ⭐⭐ — Run these two lines, then run them again. The numbers should be identical every time. Explain in a comment why setting the seed makes that happen.

np.random.seed(7)
np.random.randint(100, size=(3, 3))

In [62]:
np.random.seed(7)               # the seed is making the array's numbers unchangable so that's why it gives the same result once running
np.random.randint(100, size=(3, 3))    

array([[47, 68, 25],
       [67, 83, 23],
       [92, 57, 14]], dtype=int32)

# 3. Indexing & Slicing

In [64]:

np.random.seed(0)
M = np.random.randint(1, 50, size=(5, 6))
M

array([[45, 48,  1,  4,  4, 40],
       [10, 20, 22, 37, 24,  7],
       [25, 25, 13,  2, 39, 40],
       [24, 47, 25, 18, 38, 26],
       [14,  9, 10, 21, 17,  6]], dtype=int32)

Exercise 3.1 ⭐ — From M, grab the very first element (top-left) and the very last element (bottom-right). Hint: negative indices count from the end.

In [72]:
M[0,0]

np.int32(45)

In [85]:
M[-1,-1]

np.int32(6)

xercise 3.2 ⭐ — Pull out the third row of M (remember rows are zero-indexed) and, separately, the second column.

In [ ]:
M[2]   #third row

array([25, 25, 13,  2, 39, 40], dtype=int32)

In [ ]:
M[:,1]   # second column

array([48, 20, 25, 47,  9], dtype=int32)

Exercise 3.3 ⭐⭐ — Slice out the top-left 2 x 3 block of M (first 2 rows, first 3 columns) in a single expression.

In [101]:
M.shape

(5, 6)

In [112]:
M[:2:,:3]

array([[45, 48,  1],
       [10, 20, 22]], dtype=int32)

Exercise 3.4 ⭐⭐⭐ — Create a 4D array A of shape (2, 3, 4, 5) of random integers 0–9. Then, using slicing with :, keep everything except the last two numbers of the final dimension (so the result's last dimension has length 3).

In [115]:
A = np.random.randint(10, size = (2,3,4,5))
A 

array([[[[5, 9, 9, 2, 0],
         [9, 1, 9, 0, 6],
         [0, 4, 8, 4, 3],
         [3, 8, 8, 7, 0]],

        [[3, 8, 7, 7, 1],
         [8, 4, 7, 0, 4],
         [9, 0, 6, 4, 2],
         [4, 6, 3, 3, 7]],

        [[8, 5, 0, 8, 5],
         [4, 7, 4, 1, 3],
         [3, 9, 2, 5, 2],
         [3, 5, 7, 2, 7]]],


       [[[1, 6, 5, 0, 0],
         [3, 1, 9, 9, 6],
         [6, 7, 8, 8, 7],
         [0, 8, 6, 8, 9]],

        [[8, 3, 6, 1, 7],
         [4, 9, 2, 0, 8],
         [2, 7, 8, 4, 4],
         [1, 7, 6, 9, 4]],

        [[1, 5, 9, 7, 1],
         [3, 5, 7, 3, 6],
         [6, 7, 9, 1, 9],
         [6, 0, 3, 8, 4]]]], dtype=int32)

In [117]:
A.shape

(2, 3, 4, 5)

In [138]:
A[:,:,:,:3]

array([[[[5, 9, 9],
         [9, 1, 9],
         [0, 4, 8],
         [3, 8, 8]],

        [[3, 8, 7],
         [8, 4, 7],
         [9, 0, 6],
         [4, 6, 3]],

        [[8, 5, 0],
         [4, 7, 4],
         [3, 9, 2],
         [3, 5, 7]]],


       [[[1, 6, 5],
         [3, 1, 9],
         [6, 7, 8],
         [0, 8, 6]],

        [[8, 3, 6],
         [4, 9, 2],
         [2, 7, 8],
         [1, 7, 6]],

        [[1, 5, 9],
         [3, 5, 7],
         [6, 7, 9],
         [6, 0, 3]]]], dtype=int32)

In [139]:
A[:,:,:,:3].shape

(2, 3, 4, 3)

# 4. Arithmetic & Broadcasting

In [140]:

v = np.array([10, 20, 30])
B = np.array([[1, 2, 3],
              [4, 5, 6]])
v, B

(array([10, 20, 30]),
 array([[1, 2, 3],
        [4, 5, 6]]))

Exercise 4.1 ⭐ — Add 100 to every element of B, then square every element of v (try both ** 2 and np.square).

In [142]:
B + 100

array([[101, 102, 103],
       [104, 105, 106]])

In [144]:
v**2

array([100, 400, 900])

In [145]:
np.square(v)

array([100, 400, 900])

Exercise 4.2 ⭐⭐ — Multiply v (shape (3,)) by B (shape (2, 3)). Before running, predict the result. Which array gets broadcast over the other, and along which axis? Write the answer as a comment.

In [148]:
v * B  # v gets broadcast over B, along axis 0, it fills the gabs by ones

array([[ 10,  40,  90],
       [ 40, 100, 180]])

Exercise 4.3 ⭐⭐ — Use floor division (//) and modulo (%) on B with the divisor 2. What does each one tell you about the numbers in B?

In [150]:
B // 2

array([[0, 1, 1],
       [2, 2, 3]])

In [151]:
B % 2

array([[1, 0, 1],
       [0, 1, 0]])

Exercise 4.4 ⭐⭐⭐ — The following will raise a ValueError:

In [152]:
C = np.ones((2, 3))
D = np.ones((3, 2))
C + D

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

First run it and read the error. Then fix it by reshaping or transposing one array so the addition works — without changing the number of elements in either array.

In [159]:
C.T + D

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

# 5. Aggregation

In [167]:

#            Math  Science  English
scores = np.array([[85, 90, 78],   # student 0
                   [70, 65, 88],   # student 1
                   [95, 80, 92],   # student 2
                   [60, 75, 70]])  # student 3
scores

array([[85, 90, 78],
       [70, 65, 88],
       [95, 80, 92],
       [60, 75, 70]])

Exercise 5.1 ⭐ — Find the mean, min, and max of all the scores in the table.

In [169]:
np.mean(scores)

np.float64(79.0)

In [171]:
np.min(scores)

np.int64(60)

In [172]:
np.max(scores)

np.int64(95)

Exercise 5.2 ⭐⭐ — Find each student's average (one number per row) and each subject's average (one number per column). Hint: this is what the axis argument is for — axis=1 collapses columns, axis=0 collapses rows.

In [175]:
student_average = np.mean(scores, axis =0)
student_average

array([77.5, 77.5, 82. ])

In [177]:
subject_average= np.mean(scores, axis =1)
subject_average

array([84.33333333, 74.33333333, 89.        , 68.33333333])

Exercise 5.3 ⭐⭐ — Compute the standard deviation and variance of all scores. Then confirm, in code, that std equals sqrt(var)

In [179]:
np.std(scores)

np.float64(10.801234497346433)

In [ ]:
np.var(scores) 

np.float64(116.66666666666667)

In [185]:
np.sqrt(np.var(scores))

np.float64(10.801234497346433)

Exercise 5.4 ⭐⭐⭐ — Speed test! Build big = np.random.random(1_000_000). Use %timeit to compare Python's built-in sum(big) against np.sum(big). Which is faster on a NumPy array, and roughly by how much?

# 6.Reshaping, Transposing & Dot Product

Exercise 6.1 ⭐ — Use np.arange to make the numbers 0 through 11, then reshape them into a 3 x 4 matrix and into a 4 x 3 matrix.

In [201]:
nums = np.arange(12)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [203]:
nums.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
nums.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Exercise 6.2 ⭐⭐ — Take your 3 x 4 matrix from above and transpose it. What shape do you get? Verify with .shape.

In [208]:
shaping = nums.reshape(3,4).T
shaping

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [209]:
shaping.shape

(4, 3)

Exercise 6.3 ⭐⭐ — Create P of shape (2, 3) and Q of shape (3, 2) (random ints 0–9). Compute their dot product with np.dot and with the @ operator, and confirm both give the same result. What shape is the output, and why?

In [213]:
P = np.random.randint(10, size =(2,3))
Q= np.random.randint(10, size =(3,2))
P , Q


(array([[1, 4, 0],
        [8, 3, 9]], dtype=int32),
 array([[5, 5],
        [1, 7],
        [8, 6]], dtype=int32))

In [215]:
np.dot(P,Q)

array([[  9,  33],
       [115, 115]], dtype=int32)

In [217]:
P @ Q

array([[  9,  33],
       [115, 115]], dtype=int32)

In [14]:
np.dot(P,Q).shape  # because they have same inner dimention

NameError: name 'np' is not defined

Exercise 6.4 ⭐⭐⭐ — You're given two (4, 3) matrices. A dot product (4,3) @ (4,3) fails because the inner dimensions don't match. Transpose one of them so the multiplication works, then state what shape the result has.

In [219]:

np.random.seed(2)
matrix1 = np.random.randint(10, size = (4,3))
matrix1

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5]], dtype=int32)

In [221]:
np.random.seed(2)
matrix2= np.random.randint(10, size = (4,3))
matrix2

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5]], dtype=int32)

In [224]:
matrix1.T@ matrix2

array([[ 88,  98,  92],
       [ 98, 145, 129],
       [ 92, 129, 135]], dtype=int32)

In [226]:
matrix_shape = matrix1.T @ matrix2 
matrix_shape.shape

(3, 3)

Exercise 6.5 ⭐⭐⭐ — Nut butter store 🥜 — A shop sells 3 products. You're given the number of jars sold each day and the price per jar. Use a dot product to compute total daily sales (£).


In [231]:

np.random.seed(0)
sales = np.random.randint(20, size=(5, 3))   # 5 days x 3 products (jars sold)
prices = np.array([10, 8, 12])               # price per jar: almond, peanut, cashew 

dot_product = sales @ prices.T
dot_product


array([240, 138, 458, 232, 142])

# 7. Comparison & Sorting 

In [16]:

np.random.seed(3)
data = np.random.randint(0, 100, size=(4, 5))
data

array([[24,  3, 56, 72,  0],
       [21, 19, 74, 41, 10],
       [21, 38, 96, 20, 44],
       [93, 39, 14, 26, 81]], dtype=int32)

Exercise 7.1 ⭐ — Create a boolean array that is True wherever data is greater than 50.

In [17]:
data > 50

array([[False, False,  True,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

Exercise 7.2 ⭐⭐ — Count how many values in data are greater than 50. Hint: np.sum on a boolean array counts the Trues. Then use the boolean mask to pull out just those values (data[mask]). 

In [23]:
mask = data > 50 
count = np.sum(mask)
values = data[mask]
values, count

(array([56, 72, 74, 96, 93, 81], dtype=int32), np.int64(6))

Exercise 7.3 ⭐⭐ — Use np.sort to sort the values within each row of data. Then use np.argsort on the first row to see the indices that would sort it.

In [25]:
np.sort(data)

array([[ 0,  3, 24, 56, 72],
       [10, 19, 21, 41, 74],
       [20, 21, 38, 44, 96],
       [14, 26, 39, 81, 93]], dtype=int32)

In [30]:
np.argsort(data[0])

array([4, 1, 0, 2, 3])

Exercise 7.4 ⭐⭐⭐ — Using np.argmax and np.argmin:

Find the index of the largest value in the whole data array (treated as flat).
Find the index of the largest value in each row (axis=1).
Find the index of the smallest value in each column (axis=0).

In [32]:
#Find the index of the largest value in the whole data array (treated as flat). 
np.argmax(data)

np.int64(12)

In [34]:
#Find the index of the largest value in each row (axis=1).
np.argmax(data, axis = 1)

array([3, 2, 2, 0])

In [36]:
# Find the index of the smallest value in each column (axis=0).
np.argmax(data, axis= 0)

array([3, 3, 2, 0, 3])